CREATE PROCEDURE ZCADPRODUTO @V_PRODUTO VARCHAR(30) = NULL, @V_DATADE VARCHAR(8) = NULL, @V_DATAATE VARCHAR(8) = NULL
AS
    
DECLARE @V_OBJ INT;
DECLARE @V_URL VARCHAR(200);
DECLARE @V_RESPONSE VARCHAR(8000);
  
SET @V_URL = 'http://10.150.0.12:8080/conector_smart/services/conn_cadprod?method=runJob&arg1=--context_param produto=' + @V_PRODUTO + '&arg2=--context_param dataate=' + @V_DATADE + '&arg3=--context_param dataate=' + @V_DATAATE
EXEC SP_OACREATE 'MSXML2.ServerXMLHttp', @V_OBJ out
EXEC SP_OAMETHOD @V_OBJ, 'OPEN', NULL, 'GET', @V_URL, FALSE
EXEC SP_OAMETHOD @V_OBJ, 'SEND'
exec SP_OAGETPROPERTY @V_OBJ, 'responseText', @V_RESPONSE out
  
select ZZTIPOREGISTRO,
PRSERVICO,
PRCODIGO,
' ' PRCODIGOREDUZIDO,
PRDESCRICAO,
PRUNIDADE,
PRCLASSIFICACAOFISCAL,
' ' PRSITUACAOTRIBUTARIAESTADUAL,
' ' PRALIQUOTAIPI,
' ' PRALIQUOTAPIS,
' ' PRALIQUOTACOFINS,
' ' PRINDICADORINCENTIVO,
' ' PRPRODUTOREDUZIDO,
' ' PRGENERO,
' ' PRCLASSE,
PRUNIDADEINVENTARIO,
' ' PRBASEUNITARIAICMSST,
' ' PRCAPACIDADE,
' ' PRCCUSTO,
' ' PRCODIGOANP,
' ' PRCODIGOANTERIOR,
PRCODIGOBARRA,
' ' PRCODIGOEMPRESA,
' ' PRCODIGOSELOIPI,
' ' PRCODIGOSERVICO,
' ' PRCONVERSAO,
' ' PREX,
' ' PRINSUMODIF,
' ' PRMVA,
PRNATUREZA,
' ' PRPERCREDUCAOBASEICMS,
' ' PRQTDESELOIPI,
' ' PRSITUACAOTRIBUTARIAFEDERAL,
PRUNIDADEMEDIDA,
' ' PRALIQUOTAICM,
' ' PRPRECOUNITARIO,
' ' PRFORMACALCULOIPI,
'AUD-PADRAO' ORIGEMDADOS
from dbo.ztemp_cadprod;
  
EXEC SP_OADESTROY @V_OBJ
  
RETURN
