CREATE PROCEDURE ZESTINVENT @V_DATADE VARCHAR(8) = NULL, @V_DATAATE VARCHAR(8) = NULL
AS
    
DECLARE @V_OBJ INT;
DECLARE @V_URL VARCHAR(200);
DECLARE @V_RESPONSE VARCHAR(8000);
  
SET @V_URL = 'http://10.150.0.12:8080/conector_smart/services/conn_estinventario?method=runJob&arg1=--context_param datade=' + @V_DATADE + '&arg2=--context_param dataate=' + @V_DATAATE
EXEC SP_OACREATE 'MSXML2.ServerXMLHttp', @V_OBJ out
EXEC SP_OAMETHOD @V_OBJ, 'OPEN', NULL, 'GET', @V_URL, FALSE
EXEC SP_OAMETHOD @V_OBJ, 'SEND'
exec SP_OAGETPROPERTY @V_OBJ, 'responseText', @V_RESPONSE out
  
select distinct
INCODIGOEMPRESA, 
INCONTAANALITICA, 
INCCUSTO,
CONVERT(VARCHAR(8), INDATAINVENTARIO, 112) INDATAINVENTARIO,
INCODIGOPRODUTO, 
INCLASSIFICACAOFISCAL, 
INUNIDADEMEDIDA, 
CONVERT (varchar(16),INQTDE,1) INQTDE,
CONVERT (varchar(16),INVALORCUSTOTOTAL,1) INVALORCUSTOTOTAL,
CONVERT (varchar(16),INVALORCUSTOUNITARIO,1) INVALORCUSTOUNITARIO,
INNATUREZA,
INSITUACAO,
INCODIGOPARTICIPANTE,
INCNPJ,
ININSCRICAO,
INUF,
INQTDEINICIAL,
INICMPROPRIO,
INICMST,
INOBSFISCAL,
' ' INVALORICMS,
' ' INQTDEPERIODO,
' ' INVALORCUSTOUNITPERIODO,
' ' INVALORICMSPERIODO ,
' ' INCSTICM,
' ' INBASEICM,
' ' INLOCALIZACAO,
' ' ORIGEMDADOS
from dbo.ztemp_estinventario;

  
EXEC SP_OADESTROY @V_OBJ
  
RETURN