CREATE PROCEDURE ZCTBLANCTOS @V_DATADE VARCHAR(8) = NULL, @V_DATAATE VARCHAR(8) = NULL
AS
    
DECLARE @V_OBJ INT;
DECLARE @V_URL VARCHAR(200);
DECLARE @V_RESPONSE VARCHAR(8000);
  
SET @V_URL = 'http://10.150.0.12:8080/conector_smart/services/conn_ctblanctos?method=runJob&arg1=--context_param datade=' + @V_DATADE + '&arg2=--context_param dataate=' + @V_DATAATE
EXEC SP_OACREATE 'MSXML2.ServerXMLHttp', @V_OBJ out
EXEC SP_OAMETHOD @V_OBJ, 'OPEN', NULL, 'GET', @V_URL, FALSE
EXEC SP_OAMETHOD @V_OBJ, 'SEND'
exec SP_OAGETPROPERTY @V_OBJ, 'responseText', @V_RESPONSE out
  
select 
LCCODIGOEMPRESA,
LCCONTAANALITICA,
LCCCUSTO,
CONVERT(VARCHAR(10), LCDATALANCAMENTO, 112) LCDATALANCAMENTO,
LCVALORLANCAMENTO,
LCDEBITOCREDITO,
LCNARQUIVAMENTO,
LCPARTICIPANTE,
LCTIPOLANCTO,
LCHISTORICOCOMPLEMENTAR,
'PADRAO' ORIGEMDADOS
from dbo.ztemp_ctblanctos

  
EXEC SP_OADESTROY @V_OBJ
  
RETURN