CREATE PROCEDURE ZCTBSALDOS @V_EXERCICIO VARCHAR(4) = NULL, @V_DATADE VARCHAR(2) = NULL, @V_DATAATE VARCHAR(2) = NULL
AS
    
DECLARE @V_OBJ INT;
DECLARE @V_URL VARCHAR(200);
DECLARE @V_RESPONSE VARCHAR(8000);
  
SET @V_URL = 'http://10.150.0.12:8080/conector_smart/services/conn_ctbsaldos?method=runJob&arg1=--context_param exercicio=' + @V_EXERCICIO + '&arg2=--context_param datade=' + @V_DATADE + '&arg3=--context_param dataate=' + @V_DATAATE
EXEC SP_OACREATE 'MSXML2.ServerXMLHttp', @V_OBJ out
EXEC SP_OAMETHOD @V_OBJ, 'OPEN', NULL, 'GET', @V_URL, FALSE
EXEC SP_OAMETHOD @V_OBJ, 'SEND'
exec SP_OAGETPROPERTY @V_OBJ, 'responseText', @V_RESPONSE out
  
select 
SDCODIGOEMPRESA,
SDCONTAANALITICA,
SDDATASALDOINICIAL,
SDVALORTOTALCREDITO,
SDVALORTOTALDEBITO,
SDVALORSALDOFINAL,
SDINDICADORDCDBFINAL,
'PADRAO' ORIGEMDADOS
from dbo.ztemp_ctbsaldos

  
EXEC SP_OADESTROY @V_OBJ
  
RETURN