CREATE PROCEDURE ZCADCLIFOR @V_DATADE VARCHAR(8) = NULL, @V_DATAATE VARCHAR(8) = NULL
AS
    
DECLARE @V_OBJ INT;
DECLARE @V_URL VARCHAR(200);
DECLARE @V_RESPONSE VARCHAR(8000);
  
SET @V_URL = 'http://10.150.0.12:8080/conector_smart/services/conn_cadclifor?method=runJob&arg1=--context_param datade=' + @V_DATADE + '&arg2=--context_param dataate=' + @V_DATAATE
EXEC SP_OACREATE 'MSXML2.ServerXMLHttp', @V_OBJ out
EXEC SP_OAMETHOD @V_OBJ, 'OPEN', NULL, 'GET', @V_URL, FALSE
EXEC SP_OAMETHOD @V_OBJ, 'SEND'
exec SP_OAGETPROPERTY @V_OBJ, 'responseText', @V_RESPONSE out
  
select 
ZZTIPOREGISTRO,
CFCODIGO,
CFCGCCPF,
CFINSCRICAOESTADUAL,
CFINSCRICAOMUNICIPAL,
CFRAZAOSOCIAL,
CFNOMEFANTASIA,
CFNOMELOGRADOURO,
' ' CFNUMEROLOGRADOURO,
' ' CFCOMPLEMENTO,
CFBAIRRO,
CFMUNICIPIO,
CFUNIDADEFEDERACAO,
CFCEP,
CFCODIGOPAIS,
CFPAIS,
' ' CFCEI,
CFCODIGOIBGE,
' ' CFCODIGOSUFRAMA,
' ' CFTIPOLOGRAD,
' ' CFTIPOBAIRRO,
CFCATEGORIARELACIONADA,
' ' CFCODIGODES,
' ' CFCODRETENCAOIRRF,
' ' CFNIT,
' ' CFSUFRAMA,
' ' CFCEPCXP,
' ' CFCXPOSTAL,
' ' CFTELEFONE,
' ' CFFAX,
' ' CFRELACIONAMENTO,
' ' CFINICIORELACIONA,
' ' CFFIMRELACIONA,
' ' CFINDFOMEZERO,
' ' CFCODIGOSERVICO,
' ' CFMODELODOCUMENTO,
' ' CFTIPODOCUMENTO,
' ' CFSERIEDOCUMENTO,
' ' CFVALORSERVICO,
' ' CFCONDICAOPAGTO,
' ' CFINCIDEPCC,
' ' CFINCIDEPIS,
' ' CFINCIDECOFINS,
' ' CFINCIDECSLL,
' ' CFINCIDEIRRF,
' ' CFINCIDEINSS,
' ' CFINCIDEISS,
' ' CFCODRETENCAOINSS,
' ' CFALIQUOTA,
' ' CFALIQUOTAIRRF,
' ' CFALIQUOTAINSS,
' ' CFCODIGOCONTABIL,
' ' CFCONSUMIDOR,
' ' CFCONTRIBUINTE,
' ' CFINSCRICAOSUBSTITUTO,
' ' CFMUNICIPIOZFM,
' ' CFREGIMETRIBUT,
' ' CFMUNICIPIOESTADUAL,
' ' CFEMAIL,
' ' CFCATEGORIASCANC,
' ' CFCORRESPONDENCIA,
' ' CFDESCSERVICO,
' ' CFCNAE,
' ' CFINDRETENCAOISS,
'PADRAO' ORIGEMDADOS
from dbo.ztemp_cadclifor;
  
EXEC SP_OADESTROY @V_OBJ
  
RETURN



------------------------------------------------------------



EXEC ZCADCLIFOR